baseurl = "http://localhost:1313"
languageCode = "en"
title = "Blog"
author = "yoojene"
copyright = "Eugene Cross All rights reserved."
theme = "hugo-zen"

[params]
  logo      = "/images/sketchface.jpg"
  twitter   = "https://twitter.com/yoojene"
  github    = "https://github.com/yoojene/"
  email     = "eugene.cross@gmail.com"